version: '3'

volumes:
  bundle:
  db:
  webpacker:


services:
  db:
    image: technical_test_v0_db_1
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true


  webpacker:
    image: technical_test_v0_webpacker_1
    build: .
    command: bundle exec /bin/webpack-dev-server
    env_file:
      - 'app.env'
    volumes:
      - .:/app
    ports:
      - 3035:3035

  web: &rails
    image: technical_test_v0_web_1
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    tmpfs: /app/tmp
    depends_on:
      - db
      - webpacker

    env_file:
      - 'app.env'
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
          - NODE_ENV=development
          - RAILS_ENV=development
          - WEBPACKER_DEV_SERVER_HOST=webpacker